chore(docs): provide docs on how to handle unused `FnOnce`
Synphonyte/leptos-use pull request #134
Opened 2024-07-24 16:58 UTC by EstebanBorai

Updates https://leptos-use.rs/sensors/on_click_outside.html documentation to explain the origin of:

```
unused implementer of `FnOnce` that must be used
closures are lazy and do nothing unless called
```

And also provide a workaround.

2024-07-24 19:14 UTC, maccesch requested changes
Thank you so much for improving the docs!

2024-07-24 19:14 UTC, maccesch commented on src/on_click_outside.rs
> +/// let _ = on_click_outside(target, move |event| { log!("{:?}", event); });
I left this out on purpose for the sake of clarity. The below mentioned error message is a standard Rust thing that will let programmers know what to do. Also its just a warning. I don't want to include too much Rust learning material into the docs so they can be as concise as possible.

2024-07-24 19:14 UTC, maccesch commented on src/on_click_outside.rs
> +/// > `on_click_outside` and  `on_click_outside_with_options` returns a closure that you can call to stop
I do think that we can include this not though.

2024-07-24 19:14 UTC, maccesch commented on src/on_click_outside.rs
> +/// let _ = on_click_outside_with_options(
again, left out for conciseness

2024-07-25 00:17 UTC, EstebanBorai commented
> Thank you so much for improving the docs!

Hi @maccesch! Thanks for the quick reply, based on the comments Im a bit unsure on how to move forward with this PR.

As I understand the goal is not to encourage users to use `let _`?

2024-07-25 10:07 UTC, maccesch commented
Exactly. No need to include it in the docs because this is standard Rust practice anyway

2024-07-25 13:58 UTC, maccesch commented
Oh I just realized I mistyped. I wanted to say that we could include the note about the returned stop function though. Sorry!

2024-07-26 03:14 UTC, EstebanBorai commented
> Oh I just realized I mistyped. I wanted to say that we could include the note about the returned stop function though. Sorry!

Oh! No worries!

2024-07-27 16:30 UTC, EstebanBorai commented
Hi @maccesch!

Im a bit unsure on what are the suggestions on the doc comments, Im happy to apply them!
Can you please elaborate a bit on your POV so we land this PR together?

2024-07-27 16:41 UTC, maccesch commented on src/on_click_outside.rs
> +/// > `on_click_outside` and  `on_click_outside_with_options` returns a closure that you can call to stop
Let's only include this one

2024-07-27 17:35 UTC, maccesch commented
I saw that you pushed a commit but here it still shows all three changes

2024-08-24 11:41 UTC, closed without merging