Remove use of --cfg=web_sys_unstable_apis
Synphonyte/leptos-use pull request #44
Opened 2023-11-07 10:19 UTC by feral-dot-io

ResizeObserver was stabilised in wasm-bindgen [0.2.87](https://github.com/rustwasm/wasm-bindgen/blob/main/CHANGELOG.md)

This PR removes usage of `--cfg=web_sys_unstable_apis`, enables `use_resize_observer` plus `use_element_size` and cleans up a failing test.

2023-11-08 00:01 UTC, rakshith-ravi commented
If you're depending on wasm-bindgen 0.2.87 onwards, we should probably also update the dependency to mark it as `^0.2.87`

2023-11-08 11:41 UTC, feral-dot-io commented
That's a good point, thanks. I've [specified the minimum version](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio).

2023-11-09 16:39 UTC, maccesch requested changes
Thanks for this! I have a few little changes if I can bother you.

2023-11-09 16:39 UTC, maccesch commented on template/.ffizer.yaml
> -  - name: unstable_apis
This shouldn't be removed as we might have to use unstable apis in some functions in the future

2023-11-09 16:39 UTC, maccesch commented on template/src/{{ module }}/{{ function_name }}.ffizer.hbs.rs
> -/// > This function requires `--cfg=web_sys_unstable_apis` to be activated as
same here

2023-11-09 16:39 UTC, maccesch commented on Cargo.toml
> +wasm-bindgen = "0.2.87"
libraries shouldn't specify patch versions in their Cargo.toml as it's going to be ignored anyway

2023-11-09 16:40 UTC, maccesch commented
> That's a good point, thanks. I've [specified the minimum version](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio).

I've also specified this in the review. But in leptos-use this shouldn't be specified. It should be specified in the examples instead.

2023-11-10 07:37 UTC, rakshith-ravi commented on Cargo.toml
> +wasm-bindgen = "0.2.87"
True, but this does not mean that the version is pinned in any sense of it. In fact, I specifically wanted to mention `^0.2.87` as the version because that implies "any version above `0.2.87` will do". What you're referring to is `=0.2.87` which will pin the version to exactly that. That is definitely not what we want here. But since we're using dependencies introduced in 0.2.87, I think we should mention the version as `^0.2.87`

2023-11-10 11:23 UTC, maccesch commented on Cargo.toml
> +wasm-bindgen = "0.2.87"
Yes, but I think it should be in the examples' Cargo.toml, not in the lib's.

2023-11-10 17:15 UTC, feral-dot-io commented on template/.ffizer.yaml
> -  - name: unstable_apis
Sure thing -- I've reverted this

2023-11-10 17:15 UTC, feral-dot-io commented on template/src/{{ module }}/{{ function_name }}.ffizer.hbs.rs
> -/// > This function requires `--cfg=web_sys_unstable_apis` to be activated as
Also reverted.

2023-11-10 17:47 UTC, maccesch commented on Cargo.toml
> +wasm-bindgen = "0.2.87"
@rakshith-ravi was right, this seems to be good

2023-11-10 21:00 UTC, merged

2023-11-11 10:23 UTC, rakshith-ravi commented on Cargo.toml
> +wasm-bindgen = "0.2.87"
But even then, shouldn't the version be mentioned as `^0.2.87`? (Emphasis on the caret). Idk if it's the same as leaving it at `0.2.87` without the caret

2023-11-11 10:25 UTC, feral-dot-io commented on Cargo.toml
> +wasm-bindgen = "0.2.87"
They're the same. Please see the docs here: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements

> ^1.2.3 is exactly equivalent to 1.2.3

2023-11-11 10:28 UTC, rakshith-ravi commented on Cargo.toml
> +wasm-bindgen = "0.2.87"
Ahh, my bad

2023-11-11 10:32 UTC, feral-dot-io commented on Cargo.toml
> +wasm-bindgen = "0.2.87"
No, you're good! :) Thanks for your input on this.