Added use-cookie
Synphonyte/leptos-use pull request #69
Opened 2024-01-21 12:12 UTC by rakshith-ravi

Fixed #33 

Finally got the time for it.

Let me know if this implementation is okay. If it is, I'll add the docs for it

2024-01-21 15:06 UTC, maccesch requested changes
This is awesome! Thanks! I found two minor improvements.

As for docs and example you can get a lot of the way there by using the create function template. I'd suggest moving the current use_cookie.rs function some place temporary and then use https://github.com/Synphonyte/leptos-use#new-function-template to generate the boilerplate. Then copy the code back into the generated sceleton.

2024-01-21 15:06 UTC, maccesch commented on src/use_cookie.rs
> +        let document: web_sys::HtmlDocument = js_value.unchecked_into();
There's actually a [`document()` function](https://docs.rs/leptos/latest/leptos/fn.document.html)

2024-01-21 15:06 UTC, maccesch commented on src/use_cookie.rs
> +pub struct UseCookie {
Since there's only one field we can directly return `Option<Cookie<'static>>` from the function.

2024-01-21 15:08 UTC, maccesch commented on Cargo.toml
> +storage = ["serde", "serde_json", "web-sys/StorageEvent"]
This has been removed. You might have mismerged this. Please remove.

2024-01-21 15:19 UTC, rakshith-ravi commented on Cargo.toml
> +storage = ["serde", "serde_json", "web-sys/StorageEvent"]
My bad. I'll remove it. Started this off back in 0.7 and rebased with 0.9 lol

2024-01-21 16:05 UTC, rakshith-ravi commented on src/use_cookie.rs
> +        let document: web_sys::HtmlDocument = js_value.unchecked_into();
Done

2024-01-21 16:21 UTC, maccesch reviewed
Great, we're almost there! A little bit of nagging... 😄

2024-01-21 16:21 UTC, maccesch commented on .ffizer/options.yaml
I'm not sure if this is a new version of ffizer that did this but please remove this .ffizer folder and add it to .gitignore

2024-01-21 16:21 UTC, maccesch commented on src/use_cookie.rs
> +///
Please add a short one-line summary of what this function does here. This will be used in the "Functions" chapter of the book. Please compare any other function for how to do it.

2024-01-21 16:24 UTC, rakshith-ravi commented
> A little bit of nagging... 😄

Not at all! I'd prefer if you keep suggesting changes. Don't want to merge a half-baked PR. I'd want it to be perfect before it gets merged

2024-01-23 15:14 UTC, rakshith-ravi commented on Cargo.toml
> +http = { version = "0.2", optional = true }
Btw, we need to push this to 1.0 once we start targeting leptos 0.6

2024-01-23 15:18 UTC, merged