Add `initial_value_from_url_param` option to `UseColorModeOptions`
Synphonyte/leptos-use pull request #79
Opened 2024-02-11 00:08 UTC by mondeja

Closes #78

I'm not sure if this is the best way to implement it, but seems to work fine. Any suggestions would be appreciated.

2024-02-11 00:14 UTC, mondeja commented on src/use_color_mode.rs
> +        }
This behaviour of updating the value of storage with the url param could be parametrized with an option `initial_value_from_url_to_storage` or something else.

2024-02-11 12:20 UTC, maccesch requested changes
Looks pretty good. I have added a few minor remarks

2024-02-11 12:20 UTC, maccesch commented on src/use_color_mode.rs
> +    let initial_value_from_url = match initial_value_from_url_param {
I'm pretty sure clippy will tell you here that you re-invented `.map`

2024-02-11 12:20 UTC, maccesch commented on src/use_color_mode.rs
> +        }
1. This is indeed not sth everybody might want. So yes please add an option for that.
2. removing the value here only to override any value down below seems redundant
3. please move the overriding code out of this function to make it more "pure"

2024-02-15 21:50 UTC, mondeja commented
Now looks much better.

2024-02-16 02:22 UTC, merged

2024-02-16 02:22 UTC, maccesch commented
Nice work, thanks!